[[lessons]]
title = "Vim - Basic Navigation"
code = "let arr: [[i32; 5]; 5] = [\n    [0, 1, 2, 3, 4],\n    [5, 6, 7, 8, 9],\n    [0, 1, 2, 3, 4],\n    [5, 6, 7, 8, 9],\n    [0, 1, 2, 3, 4],\n];"
input = ["j", "j", "k", "l", "l", "k", "h", "h"]
cursor = [3, 11]
language = "ace/mode/rust"
keys = [
    { value = "h", tooltip = "move cursor left" },
    { value = "j", tooltip = "move cursor down" },
    { value = "k", tooltip = "move cursor up" },
    { value = "l", tooltip = "move cursor right" },
]

[[lessons]]
title = "Vim - Basic Navigation"
code = "let arr: [[i32; 5]; 5] = [\n    [0, 1, 2, 3, 4],\n    [5, 6, 7, 8, 9],\n    [0, 1, 2, 3, 4],\n    [5, 6, 7, 8, 9],\n    [0, 1, 2, 3, 4],\n];"
input = ["H", "M", "L"]
cursor = [2, 11]
language = "ace/mode/rust"
keys = [
    { value = "H", tooltip = "move cursor to top of editor" },
    { value = "M", tooltip = "move cursor to middle of editor" },
    { value = "L", tooltip = "move cursor to bottom of editor" },
]

[[lessons]]
title = "Vim - Basic Navigation"
code = "public static void processAbstractFactoryServiceProviderManagerContext() {\n     AbstractFactoryServiceProviderManager.getInstance().initializeContext();\n}"
input = ["w", "w", "w", "w"]
cursor = [0, 0]
language = "ace/mode/java"
keys = [
    { value = "w", tooltip = "jump forward to the start of the word" },
]